# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance. See the following documentation for theme and font configuration
# https://wowchemy.com/docs/getting-started/customization/

appearance:
  theme_day: Ocean  # Ocean, Minimal, Strawberry
  theme_night: Ocean
  # Optional: Minimal (modern), Classic (original Academic v1 style), 
  # Native: use device fonts for maximum performance, Mr Robot (futuristic), Rose (traditional serif)
  font: Classic      
  font_size: l   # Optional: xs, s, m, l, xl.

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Quantum'
    description: 'Targeting at quantum.'
    twitter: 'https://twitter.com/QuantumMan2018'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: 1  # Change the position of the menu. 1 for left, 2 for center, and 3 for right.
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Kun Wang. This work is licensed under {license}.'
    license:
      enable: true
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions
extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true
  isotope:     # Enable if you use the Portfolio widget or Publication filter
    enable: true

# Citation style
publications:
  date_format: January 2006
  citation_style: apa
  
# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
icon:
  pack:
    ai: true

# Configuration of project pages.
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2


#Advanced
reading_time: true
section_pager: false
profile: false
sharing: true